---
title: "Port security bypass: подключаемся к сети через любую розетку. Конспект материала с PHDays 2023"
author: "Гуляев Степан БИСО-01-20"
---

# Выступающий

Артемий Абызов из АО "Гринатом".
Специалист по тестирвоанию на проникновение

# Что такое Port Security?

Механизм аутентификации в локальных сетях по MAC-адресу.

## Действия при Port Security Violation

1. Просто не пропустить устройство
2. Еще и отправить лог по SMNP
3. Погасить интерфейс

## Как это обойти?

Подменить MAC-адрес своего устройства на адрес авторизованного устройства, чей MAC можно легко узнать(принтер например)

# Жаль это не все. Есть 802.1x

## Сущности 

1.Supplicant - клиент, который подключается

2.Аутентификатор - принимает решение о пропуске клиента

3.Сервер для аутентификации пользователя

## Этапы аутентификации

### 1.Подключение

Аутентификатор переводит порт, к которому подключились в состояние Unauthorized

### 2.Иницализация общения

Клиент и аутентификатор обмениваются идентификатором и передают его на сервер

### 3.Договор с сервером

Клиент и сервер договариваются от методе подключения

### 4.Аутентификация

Порт перводится в состояниe Authorized

## Методы аутентификации 

### 1.EAP-MD5

Сервер присылает случайную строку-challenge, которая передается клиенту, который конактенирует ее со своим логином и паролем, а после возвращает ссерверу хэш от того, что получил. Сервер сравнивает результат с тем, который получил сам на основании имеющихся данных и если совпало - пропускает

#### Как обойти

Передача всей информации происходит в plaintext, потому ее можно перехватить и забрутить

### 2.EAP-PEAP

Создает защищенный туннель, внутри которого аутентификация происходит. Клиент обязан проверять подлинность сертификата сервера

### 3.EAP-TLS

И на клиенте и на сервере есть TLS-сертификты

### 4.MAB(MAC AUTHENTICATION BYPASS)

Если нужно подключить древнее устройство, которое не умеет работать ни с чем перечисленным ранее. Если клиент не озывается на 3 попытки по 802.1x. Аутентификатор пропустит первый фрейм и по нему узнает MAC-адрес клиента

# Атаки

## 802.1x Bypass №1

Использовать hub. Подключить к нему одного аутентифицированного клиента и одного неаутентифицированного и тогда неаутентифицрованного и тогда второй получит доступ

## 802.1x Bypass №2

### Софт 

1.Fenrir

2.Silent Bridge

### Ход атаки

Использовать не hub, а любое другое устрйоство с двумя интерфейсами. Настроить между ними bridge и настроить source NAT

Есть три интерфейса. Один к коммутатору, второй к авторизованному устройству, третий - это USB адаптер, к которому подключаемся по ssh.

1. Поднимаем бридж

2. Через tcpdump узнаем адреса: MAC default gateaway, IP легитимного клиента, MAC легитимного клиента и MAC свитча 

3. Получаем интерактивный доступ к сети

(Примечание, авторизованный клиент не должен уходить в сон)

## Атака на MD-5

Пока идет постоянная аутентификация - брутить

### Способ 1

Заставить клиента постоянно переподключаться

### Способ 2 

Физически перевтыкать провод(использовать механический сплиттер)

# 802.1x-2010

Содержит новые механизмы защиты:

1. Шифрование на канальном уровне

2. Проверка целостности пакетов

Обход этих механизмов - это работа на физическом  уровне со сплиттерами(переключение на физическом уровне, сниффер тоже на физическом уровне)

## 802.1x-2010 Bypass №3

Отключить клиента при помощи сплиттера и при помощи сниффера читать все то, что он при отключении пытается послать, а потом брутим. А потом можно выключить клиента из сети полностью 

## Атака Rogue Gateaway

Поднять на своем компьютере фейковый сервер иднетификации и уводим трафик на себя. Получаем данные, отключаем его от сети и подключаемся к сверверу сами, теперь мы авторизованный клиент

# Примечания

1. В случае с подключением по сертификатам можно использовать способы выше, но это получится только если клиент не имеет собственного сертификата и имеет место мисконфигурация

2. Шторм контроль не мешает подключению(наверное?)

3. Подразумевает атака в нерабочее время или если подключение изначального клиента неважно

4. Защититься можно используя аутентификацию по сертификатам 









